In [1]:
import pandas as pd

In [135]:
df = pd.read_csv(r'D:\DS\DataSets\netflix_titles.csv')

In [136]:
df.shape

(8807, 12)

In [137]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   object
 1   type          8807 non-null   object
 2   title         8807 non-null   object
 3   director      6173 non-null   object
 4   cast          7982 non-null   object
 5   country       7976 non-null   object
 6   date_added    8797 non-null   object
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   object
 9   duration      8804 non-null   object
 10  listed_in     8807 non-null   object
 11  description   8807 non-null   object
dtypes: int64(1), object(11)
memory usage: 825.8+ KB

In [138]:
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [139]:
df.isna().sum()

show_id            0
type               0
title              0
director        2634
cast             825
country          831
date_added        10
release_year       0
rating             4
duration           3
listed_in          0
description        0
dtype: int64

In [140]:
df.columns = map(str.capitalize,df.columns)
df.head()

,Show_id,Type,Title,Director,Cast,Country,Date_added,Release_year,Rating,Duration,Listed_in,Description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [141]:
#No  Way to fill NaN value columns so dropping all the Nan values.
df.dropna(inplace = True)

In [142]:
df.isna().sum()

Show_id         0
Type            0
Title           0
Director        0
Cast            0
Country         0
Date_added      0
Release_year    0
Rating          0
Duration        0
Listed_in       0
Description     0
dtype: int64

# Data Cleaning

In [143]:
df.head()

,Show_id,Type,Title,Director,Cast,Country,Date_added,Release_year,Rating,Duration,Listed_in,Description
7,s8,Movie,Sankofa,Haile Gerima,"Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...","United States, Ghana, Burkina Faso, United Kin...","September 24, 2021",1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies","On a photo shoot in Ghana, an American model s..."
8,s9,TV Show,The Great British Baking Show,Andy Devonshire,"Mel Giedroyc, Sue Perkins, Mary Berry, Paul Ho...",United Kingdom,"September 24, 2021",2021,TV-14,9 Seasons,"British TV Shows, Reality TV",A talented batch of amateur bakers face off in...
9,s10,Movie,The Starling,Theodore Melfi,"Melissa McCarthy, Chris O'Dowd, Kevin Kline, T...",United States,"September 24, 2021",2021,PG-13,104 min,"Comedies, Dramas",A woman adjusting to life after a loss contend...
12,s13,Movie,Je Suis Karl,Christian Schwochow,"Luna Wedler, Jannis Niewöhner, Milan Peschel, ...","Germany, Czech Republic","September 23, 2021",2021,TV-MA,127 min,"Dramas, International Movies",After most of her family is murdered in a terr...
24,s25,Movie,Jeans,S. Shankar,"Prashanth, Aishwarya Rai Bachchan, Sri Lakshmi...",India,"September 21, 2021",1998,TV-14,166 min,"Comedies, International Movies, Romantic Movies",When the father of the man she loves insists t...

In [144]:
df.Show_id = df['Show_id'].apply(lambda x : x[1:])
df.Show_id = df.Show_id.astype('int')

In [145]:
df.Type.unique()
# There is only 2 and looks good so moving to other columns

array(['Movie', 'TV Show'], dtype=object)

In [146]:
df.Date_added = pd.to_datetime(df.Date_added)
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5332 entries, 7 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Show_id       5332 non-null   int32
 1   Type          5332 non-null   object
 2   Title         5332 non-null   object
 3   Director      5332 non-null   object
 4   Cast          5332 non-null   object
 5   Country       5332 non-null   object
 6   Date_added    5332 non-null   datetime64[ns]
 7   Release_year  5332 non-null   int64
 8   Rating        5332 non-null   object
 9   Duration      5332 non-null   object
 10  Listed_in     5332 non-null   object
 11  Description   5332 non-null   object
dtypes: datetime64[ns](1), int32(1), int64(1), object(9)
memory usage: 520.7+ KB

In [147]:
df.head()

,Show_id,Type,Title,Director,Cast,Country,Date_added,Release_year,Rating,Duration,Listed_in,Description
7,8,Movie,Sankofa,Haile Gerima,"Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...","United States, Ghana, Burkina Faso, United Kin...",2021-09-24,1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies","On a photo shoot in Ghana, an American model s..."
8,9,TV Show,The Great British Baking Show,Andy Devonshire,"Mel Giedroyc, Sue Perkins, Mary Berry, Paul Ho...",United Kingdom,2021-09-24,2021,TV-14,9 Seasons,"British TV Shows, Reality TV",A talented batch of amateur bakers face off in...
9,10,Movie,The Starling,Theodore Melfi,"Melissa McCarthy, Chris O'Dowd, Kevin Kline, T...",United States,2021-09-24,2021,PG-13,104 min,"Comedies, Dramas",A woman adjusting to life after a loss contend...
12,13,Movie,Je Suis Karl,Christian Schwochow,"Luna Wedler, Jannis Niewöhner, Milan Peschel, ...","Germany, Czech Republic",2021-09-23,2021,TV-MA,127 min,"Dramas, International Movies",After most of her family is murdered in a terr...
24,25,Movie,Jeans,S. Shankar,"Prashanth, Aishwarya Rai Bachchan, Sri Lakshmi...",India,2021-09-21,1998,TV-14,166 min,"Comedies, International Movies, Romantic Movies",When the father of the man she loves insists t...

In [148]:
df['Duration'].unique()

array(['125 min', '9 Seasons', '104 min', '127 min', '166 min', '103 min',
       '97 min', '106 min', '96 min', '124 min', '116 min', '98 min',
       '91 min', '115 min', '122 min', '99 min', '88 min', '100 min',
       '102 min', '93 min', '95 min', '85 min', '83 min', '182 min',
       '147 min', '90 min', '128 min', '143 min', '119 min', '114 min',
       '118 min', '108 min', '117 min', '121 min', '142 min', '113 min',
       '154 min', '120 min', '82 min', '94 min', '109 min', '101 min',
       '105 min', '86 min', '229 min', '76 min', '89 min', '110 min',
       '156 min', '112 min', '129 min', '107 min', '1 Season', '135 min',
       '136 min', '165 min', '150 min', '133 min', '145 min', '92 min',
       '2 Seasons', '64 min', '59 min', '111 min', '87 min', '148 min',
       '189 min', '141 min', '130 min', '7 Seasons', '68 min', '131 min',
       '126 min', '155 min', '123 min', '84 min', '4 Seasons', '13 min',
       '77 min', '74 min', '49 min', '72 min', '78 min', '70 min',
       '132 min', '140 min', '81 min', '138 min', '149 min', '15 min',
       '224 min', '162 min', '60 min', '65 min', '137 min', '75 min',
       '32 min', '158 min', '164 min', '173 min', '181 min', '73 min',
       '6 Seasons', '24 min', '80 min', '139 min', '151 min', '22 min',
       '134 min', '58 min', '52 min', '71 min', '161 min', '53 min',
       '8 min', '46 min', '57 min', '28 min', '66 min', '50 min',
       '79 min', '26 min', '54 min', '48 min', '45 min', '171 min',
       '42 min', '27 min', '51 min', '69 min', '47 min', '33 min',
       '44 min', '29 min', '146 min', '61 min', '63 min', '157 min',
       '203 min', '25 min', '30 min', '62 min', '194 min', '55 min',
       '5 Seasons', '15 Seasons', '177 min', '237 min', '195 min',
       '253 min', '152 min', '67 min', '190 min', '160 min', '208 min',
       '180 min', '144 min', '174 min', '170 min', '192 min', '209 min',
       '187 min', '185 min', '172 min', '186 min', '8 Seasons', '193 min',
       '176 min', '17 min', '56 min', '169 min', '40 min', '20 min',
       '12 min', '168 min', '153 min', '159 min', '214 min', '31 min',
       '163 min', '14 min', '179 min', '38 min', '23 min', '3 Seasons',
       '43 min', '200 min', '196 min', '167 min', '41 min', '37 min',
       '35 min', '178 min', '228 min', '18 min', '205 min', '201 min',
       '191 min'], dtype=object)

In [149]:
# To Rearrange the duration, we are considering 8 episodes per season and each episode is 30 minutes
def DurationChange(Duration):
    tmp = Duration.split(' ')
    if tmp[1] == 'min' or tmp[1] == 'Min':
        return tmp[0]
    elif tmp[1] == 'Seasons' or tmp[1] == 'Season':
        return int(tmp[0]) * 8 * 30

In [150]:
df.Duration = df['Duration'].apply(lambda x : DurationChange(x))
df.Duration = df.Duration.astype('float')
df['Duration'] = df['Duration'].apply(lambda x : "{:.1f}".format(x/60))