# Pandas

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('D:\DS\Study\Pnadas\Data\survey_results_public.csv',index_col = 'Respondent')

In [6]:
# By default jupyter will show only 20 columns
#shape method gives the no of rows and columns
df.shape

(88883, 84)

In [7]:
#info method gives the details of the column
df.tail(10)

,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,...,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
Respondent,,,,,,,,,,,,,,,,,,,,,
88062,NaN,No,Never,"OSS is, on average, of LOWER quality than prop...",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88076,NaN,No,Never,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88182,NaN,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed part-time,Pakistan,NaN,"Secondary school (e.g. American high school, G...",NaN,Taken an online course in programming or softw...,...,Not applicable - I did not use Stack Overflow ...,Courses on technologies you're interested in,NaN,Man,No,Straight / Heterosexual,NaN,Yes,Too short,Neither easy nor difficult
88212,NaN,No,Less than once per year,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Spain,No,"Secondary school (e.g. American high school, G...",NaN,"Taught yourself a new language, framework, or ...",...,NaN,Tech articles written by other developers;Indu...,40.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
88282,NaN,Yes,Once a month or more often,The quality of OSS and closed source software ...,"Not employed, but looking for work",United States,No,Some college/university study without earning ...,"Computer science, computer engineering, or sof...","Taught yourself a new language, framework, or ...",...,Just as welcome now as I felt last year,NaN,NaN,Man,No,Straight / Heterosexual,NaN,No,Too short,Neither easy nor difficult
88377,NaN,Yes,Less than once a month but more than once per ...,The quality of OSS and closed source software ...,"Not employed, and not looking for work",Canada,No,Primary/elementary school,NaN,"Taught yourself a new language, framework, or ...",...,NaN,Tech articles written by other developers;Tech...,NaN,Man,No,NaN,NaN,No,Appropriate in length,Easy
88601,NaN,No,Never,The quality of OSS and closed source software ...,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88802,NaN,No,Never,NaN,Employed full-time,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88816,NaN,No,Never,"OSS is, on average, of HIGHER quality than pro...","Independent contractor, freelancer, or self-em...",NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88863,NaN,Yes,Less than once per year,"OSS is, on average, of HIGHER quality than pro...","Not employed, and not looking for work",Spain,"Yes, full-time","Professional degree (JD, MD, etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,...,Somewhat less welcome now than last year,Tech articles written by other developers;Indu...,18.0,Man,No,Straight / Heterosexual,Hispanic or Latino/Latina;White or of European...,No,Appropriate in length,Easy

In [8]:
# to show the full colunms we can use max_columns
pd.set_option('display.max_columns',85)#we are giving how many columns to show

In [9]:
df.head(2)

,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,OrgSize,DevType,YearsCode,Age1stCode,YearsCodePro,CareerSat,JobSat,MgrIdiot,MgrMoney,MgrWant,JobSeek,LastHireDate,LastInt,FizzBuzz,JobFactors,ResumeUpdate,CurrencySymbol,CurrencyDesc,CompTotal,CompFreq,ConvertedComp,WorkWeekHrs,WorkPlan,WorkChallenge,WorkRemote,WorkLoc,ImpSyn,CodeRev,CodeRevHrs,UnitTests,PurchaseHow,PurchaseWhat,LanguageWorkedWith,LanguageDesireNextYear,DatabaseWorkedWith,DatabaseDesireNextYear,PlatformWorkedWith,PlatformDesireNextYear,WebFrameWorkedWith,WebFrameDesireNextYear,MiscTechWorkedWith,MiscTechDesireNextYear,DevEnviron,OpSys,Containers,BlockchainOrg,BlockchainIs,BetterLife,ITperson,OffOn,SocialMedia,Extraversion,ScreenName,SOVisit1st,SOVisitFreq,SOVisitTo,SOFindAnswer,SOTimeSaved,SOHowMuchTime,SOAccount,SOPartFreq,SOJobs,EntTeams,SOComm,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
Respondent,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,"Taught yourself a new language, framework, or ...",NaN,NaN,4,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTML/CSS;Java;JavaScript;Python,C;C++;C#;Go;HTML/CSS;Java;JavaScript;Python;SQL,SQLite,MySQL,MacOS;Windows,Android;Arduino;Windows,Django;Flask,Flask;jQuery,Node.js,Node.js,IntelliJ;Notepad++;PyCharm,Windows,I do not use containers,NaN,NaN,Yes,"Fortunately, someone else has that title",Yes,Twitter,Online,Username,2017,A few times per month or weekly,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,31-60 minutes,No,NaN,"No, I didn't know that Stack Overflow had a jo...","No, and I don't know what those are",Neutral,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
2,I am a student who is learning to code,No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",Bosnia and Herzegovina,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,Taken an online course in programming or softw...,NaN,"Developer, desktop or enterprise applications;...",NaN,17,NaN,NaN,NaN,NaN,NaN,NaN,I am actively looking for a job,I've never had a job,NaN,NaN,Financial performance or funding status of the...,"Something else changed (education, award, medi...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C++;HTML/CSS;Python,C++;HTML/CSS;JavaScript;SQL,NaN,MySQL,Windows,Windows,Django,Django,NaN,NaN,Atom;PyCharm,Windows,I do not use containers,NaN,Useful across many domains and could change ma...,Yes,Yes,Yes,Instagram,Online,Username,2017,Daily or almost daily,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,11-30 minutes,Yes,A few times per month or weekly,"No, I knew that Stack Overflow had a job board...","No, and I don't know what those are","Yes, somewhat",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,19.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult

In [10]:
df1 = pd.read_csv('D:\DS\Study\Pnadas\Data\survey_results_schema.csv')

In [11]:
df1

          Column                                       QuestionText
0     Respondent  Randomized respondent ID number (not in order ...
1     MainBranch  Which of the following options best describes ...
2       Hobbyist                            Do you code as a hobby?
3    OpenSourcer        How often do you contribute to open source?
4     OpenSource  How do you feel about the quality of open sour...
..           ...                                                ...
80     Sexuality  Which of the following do you currently identi...
81     Ethnicity  Which of the following do you identify as? Ple...
82    Dependents  Do you have any dependents (e.g., children, el...
83  SurveyLength  How do you feel about the length of the survey...
84    SurveyEase  How easy or difficult was this survey to compl...

[85 rows x 2 columns]

In [12]:
df1.loc[[0,1,2,3],'QuestionText']

0    Randomized respondent ID number (not in order ...
1    Which of the following options best describes ...
2                              Do you code as a hobby?
3          How often do you contribute to open source?
Name: QuestionText, dtype: object

In [13]:
pd.set_option('display.max_rows',85)

In [14]:
df1

                    Column                                       QuestionText
0               Respondent  Randomized respondent ID number (not in order ...
1               MainBranch  Which of the following options best describes ...
2                 Hobbyist                            Do you code as a hobby?
3              OpenSourcer        How often do you contribute to open source?
4               OpenSource  How do you feel about the quality of open sour...
5               Employment  Which of the following best describes your cur...
6                  Country          In which country do you currently reside?
7                  Student  Are you currently enrolled in a formal, degree...
8                  EdLevel  Which of the following best describes the high...
9           UndergradMajor  What was your main or most important field of ...
10                EduOther  Which of the following types of non-degree edu...
11                 OrgSize  Approximately how many people are employed by ...
12                 DevType  Which of the following describe you? Please se...
13               YearsCode  Including any education, how many years have y...
14              Age1stCode  At what age did you write your first line of c...
15            YearsCodePro  How many years have you coded professionally (...
16               CareerSat  Overall, how satisfied are you with your caree...
17                  JobSat  How satisfied are you with your current job? (...
18                MgrIdiot  How confident are you that your manager knows ...
19                MgrMoney  Do you believe that you need to be a manager t...
20                 MgrWant  Do you want to become a manager yourself in th...
21                 JobSeek  Which of the following best describes your cur...
22            LastHireDate  When was the last time that you took a job wit...
23                 LastInt  In your most recent successful job interview (...
24                FizzBuzz  Have you ever been asked to solve FizzBuzz in ...
25              JobFactors  Imagine that you are deciding between two job ...
26            ResumeUpdate  Think back to the last time you updated your r...
27          CurrencySymbol  Which currency do you use day-to-day? If your ...
28            CurrencyDesc  Which currency do you use day-to-day? If your ...
29               CompTotal  What is your current total compensation (salar...
30                CompFreq   Is that compensation weekly, monthly, or yearly?
31           ConvertedComp  Salary converted to annual USD salaries using ...
32             WorkWeekHrs   On average, how many hours per week do you work?
33                WorkPlan            How structured or planned is your work?
34           WorkChallenge  Of these options, what are your greatest chall...
35              WorkRemote                    How often do you work remotely?
36                 WorkLoc                    Where would you prefer to work?
37                  ImpSyn  For the specific work you do, and the years of...
38                 CodeRev           Do you review code as part of your work?
39              CodeRevHrs  On average, how many hours per week do you spe...
40               UnitTests  Does your company regularly employ unit tests ...
41             PurchaseHow  How does your company make decisions about pur...
42            PurchaseWhat  What level of influence do you, personally, ha...
43      LanguageWorkedWith  Which of the following programming, scripting,...
44  LanguageDesireNextYear  Which of the following programming, scripting,...
45      DatabaseWorkedWith  Which of the following database environments h...
46  DatabaseDesireNextYear  Which of the following database environments h...
47      PlatformWorkedWith  Which of the following platforms have you done...
48  PlatformDesireNextYear  Which of the following platforms have you done...
49      WebFrameWorkedWith  Which of the following web frameworks have you...
50  WebFrameDesireNextYear  Which of the following web frameworks have you...
51      MiscTechWorkedWith  Which of the following other frameworks, libra...
52  MiscTechDesireNextYear  Which of the following other frameworks, libra...
53              DevEnviron  Which development environment(s) do you use re...
54                   OpSys  What is the primary operating system in which ...
55              Containers  How do you use containers (Docker, Open Contai...
56           BlockchainOrg  How is your organization thinking about or imp...
57            BlockchainIs  Blockchain / cryptocurrency technology is prim...
58              BetterLife  Do you think people born today will have a bet...
59                ITperson   Are you the "IT support person" for your family?
60                   OffOn        Have you tried turning it off and on again?
61             SocialMedia        What social media site do you use the most?
62            Extraversion    Do you prefer online chat or IRL conversations?
63              ScreenName                               What do you call it?
64              SOVisit1st  To the best of your memory, when did you first...
65             SOVisitFreq  How frequently would you say you visit Stack O...
66               SOVisitTo  I visit Stack Overflow to... (check all that a...
67            SOFindAnswer  On average, how many times a week do you find ...
68             SOTimeSaved  Think back to the last time you solved a codin...
69           SOHowMuchTime  About how much time did you save? If you're no...
70               SOAccount              Do you have a Stack Overflow account?
71              SOPartFreq  How frequently would you say you participate i...
72                  SOJobs  Have you ever used or visited Stack Overflow J...
73                EntTeams  Have you ever used Stack Overflow for Enterpri...
74                  SOComm  Do you consider yourself a member of the Stack...
75           WelcomeChange  Compared to last year, how welcome do you feel...
76            SONewContent  Would you like to see any of the following on ...
77                     Age  What is your age (in years)? If you prefer not...
78                  Gender  Which of the following do you currently identi...
79                   Trans                    Do you identify as transgender?
80               Sexuality  Which of the following do you currently identi...
81               Ethnicity  Which of the following do you identify as? Ple...
82              Dependents  Do you have any dependents (e.g., children, el...
83            SurveyLength  How do you feel about the length of the survey...
84              SurveyEase  How easy or difficult was this survey to compl...

In [15]:
data = {
    'first': ['Milan','Linssie','Nithish'],
    'last' : ['victor','T','Shanmugam'],
    'email':['mv@abc.com','lt@abc.com','ns@abc.com']
}

In [16]:
df = pd.DataFrame(data)

In [17]:
df

     first       last       email
0    Milan     victor  mv@abc.com
1  Linssie          T  lt@abc.com
2  Nithish  Shanmugam  ns@abc.com

In [18]:
df.set_index('email',inplace=True)

In [19]:
df.reset_index(inplace=True)
df

        email    first       last
0  mv@abc.com    Milan     victor
1  lt@abc.com  Linssie          T
2  ns@abc.com  Nithish  Shanmugam

In [20]:
# To access any column
df['email']

0    mv@abc.com
1    lt@abc.com
2    ns@abc.com
Name: email, dtype: object

In [21]:
# another method
df.email

0    mv@abc.com
1    lt@abc.com
2    ns@abc.com
Name: email, dtype: object

In [22]:
# to access more column
df[['first','last']]

     first       last
0    Milan     victor
1  Linssie          T
2  Nithish  Shanmugam

In [23]:
df.columns # to get the column names

Index(['email', 'first', 'last'], dtype='object')

In [24]:
# to access the rows randomly
# iloc full ah vae only integers so we must give index values
#syntax iloc[[row_indexes],column_indexes]
df.iloc[0] # indexing
df.iloc[[0,1],2] # we are taking email id column for first 2 rows
df.iloc[[0,1],[0,1]] # we can give index for columns also

        email    first
0  mv@abc.com    Milan
1  lt@abc.com  Linssie

In [25]:
# loc same as iloc in here for column we must give columns names only.
df.loc[[1,2],['email','first']]

        email    first
1  lt@abc.com  Linssie
2  ns@abc.com  Nithish

In [26]:
df.head(2)

        email    first    last
0  mv@abc.com    Milan  victor
1  lt@abc.com  Linssie       T

In [27]:
# Filtering
# We are going to see some simple filtering
# We are getting hobbyist as No and will do some changes
df['Hobbyist'] == 'Yes' # it will return true if it's matching or false
df[df['Hobbyist'] == 'Yes']
# using loc we can get the required columns
filt = (df['Hobbyist'] == 'Yes')
df.loc[filt,'MainBranch']

KeyError: 'Hobbyist'

In [ ]:
# we are going to add some other conditions
#df.head(2)
filt = ((df['Hobbyist'] == 'No') & (df['OpenSourcer'] == 'Never'))
df[filt]
df[~filt]# it will give opposite of filt query

In [ ]:
# isin
cty = ['India','Canada']
filt = df['Country'].isin(cty)
df[filt]

In [ ]:
# to find a word in an string
filt = df['LanguageWorkedWith'].str.contains('Python',na = False) # we are not considering the NaN values so na = False is used
df.loc[filt,'LanguageWorkedWith']

In [ ]:
# Updating our DataFrame and columns
# renaming the columns
# df.columns = ['','',..] ella column kum name kudukanum here we have more than 85 columns so not renaming it
# upper casing the column name
df.columns = [x.upper() for x in df.columns]
df.columns # it's a permanant changes of column name

In [ ]:
# we are going to test replace method which is available in str class
#df.columns.str.replace('#','A')
df.columns.str.replace(' ','_') # replacing the space by underscore

In [ ]:
df.columns = [x.upper() for x in df.columns]
df

In [ ]:
# renaming the column
df.rename(columns = {'HOBBYIST':'Hobbyist'}) # to reflect in actual dataframe we should use inplace = True

In [ ]:
# updating our dataframe values
df.loc[2]

In [28]:
data = {
    'first': ['Milan','Linssie','Nithish'],
    'last' : ['victor','T','Shanmugam'],
    'email':['mv@abc.com','lt@abc.com','ns@abc.com']
}
df1 = pd.DataFrame(data)

In [29]:
df1

     first       last       email
0    Milan     victor  mv@abc.com
1  Linssie          T  lt@abc.com
2  Nithish  Shanmugam  ns@abc.com

In [30]:
# simple way to replace but we should replace all values
df1.loc[1] = ['Lins','Tamilmaran','LT@abc.com'] # we can't give any one of the column in this method

In [31]:
df1

     first        last       email
0    Milan      victor  mv@abc.com
1     Lins  Tamilmaran  LT@abc.com
2  Nithish   Shanmugam  ns@abc.com

In [32]:
# another method
df1.loc[1,['first','last']] = ['Linssie','T']
df1

     first       last       email
0    Milan     victor  mv@abc.com
1  Linssie          T  LT@abc.com
2  Nithish  Shanmugam  ns@abc.com

In [33]:
# .at is same as loc only
df1.at[1,'email'] = 'lt@abc.com'
df1

     first       last       email
0    Milan     victor  mv@abc.com
1  Linssie          T  lt@abc.com
2  Nithish  Shanmugam  ns@abc.com